Button
itsp-pbl-2023/mind-graph pull request #85
Opened 2023-06-20 05:58 UTC by buiha-uniexplore

ボタンのスタイルを変更しました
・丸い四角に
・色をデザインにマッチするように

2023-06-20 06:01 UTC, NapoliN requested changes
名前入力とかのフォームの方をお願いします:pray:

2023-06-20 08:23 UTC, NapoliN commented
InputFormにmarginを入れて欲しいです

2023-06-20 08:44 UTC, buiha-uniexplore commented
Marginを追加しました

2023-06-27 05:02 UTC, NapoliN commented on client/src/components/input.tsx
> +
<img width="396" alt="image" src="https://github.com/itsp-pbl-2023/mind-graph/assets/50442327/72297878-0525-4dc5-999d-26f8f7dbfa51">

フォーカスしてないときにボーダーが表示されてない

2023-06-27 05:02 UTC, NapoliN commented on client/src/pages/waiting.tsx
>          <Button text="送信" onClick={SendTheme}/>
「ゲームを開始する」ボタンをつけたならこっちはもう要らなそう

2023-06-27 05:03 UTC, motoki317 commented on client/package.json
> +    "vite": "^4.3.9"
この変更は意図通りですか？

2023-06-27 05:05 UTC, buiha-uniexplore commented on client/package.json
> +    "vite": "^4.3.9"
触ってないはずです
どっちの方が正しいですか？

2023-06-27 05:05 UTC, buiha-uniexplore commented on client/src/pages/waiting.tsx
>          <Button text="送信" onClick={SendTheme}/>
おっけーです

2023-06-27 05:25 UTC, buiha-uniexplore commented on client/package.json
> +    "vite": "^4.3.9"
main 確認すると^4.3.9が正しいらしいです

2023-06-27 05:27 UTC, NapoliN approved these changes

2023-06-27 05:28 UTC, motoki317 commented on client/package.json
> +    "vite": "^4.3.9"
ee3292ab79e6479f8110604132255d8e1b8ee80b
このコミットで入っちゃってると思います 別にpatchなので上げてもいいと思いますが...

2023-06-27 05:32 UTC, merged